name: 'Publish to GitHub Packages'
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  publish:
    name: 'Publish to GitHub Packages'
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm ci
      - name: Set up npm to publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" > .npmrc
          echo "@adamwolf:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}